import { useEffect, useMemo, useState } from "react";
import { api } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import "../styles/supervisors.css";

type Department = { id: number; name: string };
type Section = { id: number; departmentId: number; code: string; name: string; costCenter: { code: string } | null };
type Employee = { id: number; ecNo: string; name: string; designation: string; category: string; mobile: string | null; department: Department; sectionAssignment: { section: Section } | null };

export function EmployeesPage() {
  const { user } = useAuth();
  const isHod = user?.role === "HOD";
  const [departments,setDepartments]=useState<Department[]>([]); const [sections,setSections]=useState<Section[]>([]); const [employees,setEmployees]=useState<Employee[]>([]);
  const [departmentId,setDepartmentId]=useState(""); const [sectionId,setSectionId]=useState(""); const [ecNo,setEcNo]=useState(""); const [name,setName]=useState(""); const [designation,setDesignation]=useState(""); const [category,setCategory]=useState("PAYROLL"); const [mobile,setMobile]=useState(""); const [email,setEmail]=useState(""); const [search,setSearch]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){const [d,s,e]=await Promise.all([api<{departments:Department[]}>("/departments"),api<{sections:Section[]}>("/sections"),api<{employees:Employee[]}>("/employees")]);setDepartments(d.departments);setSections(s.sections);setEmployees(e.employees);}
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Could not load employees."));},[]);
  useEffect(()=>{if(isHod&&user?.departmentId)setDepartmentId(String(user.departmentId));},[isHod,user?.departmentId]);
  const eligible=sections.filter(s=>String(s.departmentId)===departmentId); const shown=useMemo(()=>employees.filter(e=>[e.ecNo,e.name,e.department.name,e.sectionAssignment?.section.name].some(v=>v?.toLowerCase().includes(search.toLowerCase()))),[employees,search]);
  return <><div className="supervisors-toolbar"><p className="muted">Register payroll employees with one canonical ecNo and one Section. HOD access is restricted to the assigned Department.</p><input className="search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employees…" /></div>{error&&<div className="error-banner">{error}</div>}{notice&&<div className="alloc-note">{notice}</div>}
    <div className="panel"><div className="panel__header"><span>Register Payroll Employee</span></div><form className="panel__body sup-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");setNotice("");try{await api("/admin/employees",{method:"POST",body:JSON.stringify({ecNo,name,departmentId:Number(departmentId),sectionId:Number(sectionId),designation,category,mobile:mobile||null,email:email||null,role:"EMPLOYEE"})});setEcNo("");setName("");setDesignation("");setMobile("");setEmail("");setNotice("Employee registered." );await load();}catch(err){setError(err instanceof Error?err.message:"Registration failed.");}finally{setBusy(false);}}}>
      <div className="sup-form__grid"><div className="sup-field"><label>Canonical ecNo</label><input required value={ecNo} onChange={e=>setEcNo(e.target.value)} /></div><div className="sup-field"><label>Full name</label><input required value={name} onChange={e=>setName(e.target.value)} /></div><div className="sup-field"><label>Department</label><select required disabled={isHod} value={departmentId} onChange={e=>{setDepartmentId(e.target.value);setSectionId("");}}><option value="">Select Department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div className="sup-field"><label>Section</label><select required value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">Select Section</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}{s.costCenter?` (${s.costCenter.code})`:""}</option>)}</select></div><div className="sup-field"><label>Designation</label><input value={designation} onChange={e=>setDesignation(e.target.value)} /></div><div className="sup-field"><label>Category</label><input value={category} onChange={e=>setCategory(e.target.value)} /></div><div className="sup-field"><label>Mobile</label><input value={mobile} onChange={e=>setMobile(e.target.value)} /></div><div className="sup-field"><label>Login email (optional)</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} /></div></div><button className="btn btn-primary" disabled={busy}>{busy?"Registering…":"Register Employee"}</button>
    </form></div>
    <div className="panel" style={{marginTop:16}}><div className="panel__header"><span>Active Employees</span><span className="panel__count">{shown.length}</span></div>{shown.length?<table className="sup-table"><thead><tr><th>ecNo</th><th>Name</th><th>Department</th><th>Section</th><th>Designation</th></tr></thead><tbody>{shown.map(e=><tr key={e.id}><td><strong>{e.ecNo}</strong></td><td>{e.name}</td><td>{e.department.name}</td><td>{e.sectionAssignment?.section.name||"Not assigned"}</td><td>{e.designation||"—"}</td></tr>)}</tbody></table>:<div className="empty-state">No employees found.</div>}</div></>;
}
