import { useCallback, useEffect, useMemo, useState } from "react";
import { api, ApiError } from "../api/client";
import "../styles/supervisors.css";

type Department = { id: number; name: string; code?: string };
type Section = { id: number; departmentId: number; code: string; name: string; costCenter?: { id: number; code: string; name: string } | null };
type Employee = { id: number; ecNo: string; name: string; employmentType?: string; active?: boolean; department?: Department };
type Supervisor = { id: number; name: string; email: string; source: string; active?: boolean; employeeId: number | null; departmentId: number | null; department: Department | null; employee: { id: number; ecNo: string; mobile?: string | null; active?: boolean; employmentType?: string; sectionAssignment?: { section: Section } | null } | null };
type Override = { id: number; employeeId: number; reason: string; revokedAt?: string | null; createdAt: string; employee: Employee; createdBy?: { name: string } | null };
type Mode = "list" | "overrides";
type Modal = { kind: "create" } | { kind: "edit"; supervisor: Supervisor } | { kind: "override" } | null;

function errorText(e: unknown) { return e instanceof ApiError && e.payload && typeof e.payload === "object" && "error" in e.payload ? String((e.payload as { error: string }).error) : e instanceof Error ? e.message : "Request failed"; }
function sectionOf(s: Supervisor) { return s.employee?.sectionAssignment?.section ?? null; }

export function SupervisorsPage() {
  const [mode, setMode] = useState<Mode>("list"); const [supervisors, setSupervisors] = useState<Supervisor[]>([]);
  const [overrides, setOverrides] = useState<Override[]>([]); const [departments, setDepartments] = useState<Department[]>([]);
  const [sections, setSections] = useState<Section[]>([]); const [employees, setEmployees] = useState<Employee[]>([]);
  const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [modal, setModal] = useState<Modal>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try {
    const [s,o,d,se,e] = await Promise.all([api<{supervisors:Supervisor[]}>("/supervisors"),api<{overrides:Override[]}>("/supervisors/overrides"),api<{departments:Department[]}>("/departments"),api<{sections:Section[]}>("/sections"),api<{employees:Employee[]}>("/employees")]);
    setSupervisors(s.supervisors); setOverrides(o.overrides); setDepartments(d.departments); setSections(se.sections); setEmployees(e.employees);
  } catch(e) { setError(errorText(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function run(fn:()=>Promise<unknown>, success?:string) { setBusy(true); setError(""); setNotice(""); try { await fn(); setModal(null); if(success)setNotice(success); await load(); } catch(e){setError(errorText(e));} finally{setBusy(false);} }
  const q=search.trim().toLowerCase();
  const shown=useMemo(()=>supervisors.filter(s=>[s.name,s.email,s.employee?.ecNo,s.department?.name,sectionOf(s)?.name].some(v=>v?.toLowerCase().includes(q))),[supervisors,q]);
  const shownOverrides=useMemo(()=>overrides.filter(o=>[o.employee.name,o.employee.ecNo,o.reason].some(v=>v?.toLowerCase().includes(q))),[overrides,q]);
  return <>
    <div className="supervisors-toolbar"><div className="supervisors-actions" role="tablist"><button type="button" className={`btn ${mode==="list"?"btn-primary":"btn-ghost"}`} onClick={()=>setMode("list")}>Supervisors</button><button type="button" className={`btn ${mode==="overrides"?"btn-primary":"btn-ghost"}`} onClick={()=>setMode("overrides")}>CLMS Overrides</button></div><div className="supervisors-actions"><input className="search-input" style={{marginBottom:0,minWidth:200}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or ecNo…" />{mode==="list"?<button className="btn btn-primary" onClick={()=>setModal({kind:"create"})}>+ Register Supervisor</button>:<button className="btn btn-primary" onClick={()=>setModal({kind:"override"})}>+ Add Override</button>}</div></div>
    <p className="muted" style={{marginTop:0}}>ecNo is the canonical employee identity. Login credentials are generated only by the delivery worker and queued for secure delivery.</p>
    {error&&<div className="error-banner">{error}</div>}{notice&&<div className="alloc-note">{notice}</div>}{loading?<div className="loading-state">Loading supervisors…</div>:mode==="list"?<SupervisorTable rows={shown} busy={busy} onEdit={s=>setModal({kind:"edit",supervisor:s})} onReset={s=>window.confirm(`Queue a credential reset for ${s.name}?`)&&run(()=>api(`/supervisors/${s.id}/credential-reset`,{method:"POST"}),"Credential reset queued.")} onDisable={s=>window.confirm(`Disable ${s.name}'s login?`)&&run(()=>api(`/supervisors/${s.id}`,{method:"DELETE"}),"Supervisor login disabled.")} />:<OverrideTable rows={shownOverrides} busy={busy} onRevoke={o=>window.confirm(`Revoke the override for ${o.employee.name}?`)&&run(()=>api(`/supervisors/overrides/${o.id}`,{method:"DELETE"}),"Override revoked.")} />}
    {modal?.kind==="create"&&<SupervisorForm departments={departments} sections={sections} busy={busy} onClose={()=>setModal(null)} onSave={body=>run(()=>api("/supervisors",{method:"POST",body:JSON.stringify(body)}),"Supervisor registered and initial credentials queued.")} />}
    {modal?.kind==="edit"&&<SupervisorForm supervisor={modal.supervisor} departments={departments} sections={sections} busy={busy} onClose={()=>setModal(null)} onSave={body=>run(()=>api(`/supervisors/${modal.supervisor.id}`,{method:"PUT",body:JSON.stringify(body)}),"Supervisor updated.")} />}
    {modal?.kind==="override"&&<OverrideForm employees={employees} busy={busy} onClose={()=>setModal(null)} onSave={body=>run(()=>api("/supervisors/overrides",{method:"POST",body:JSON.stringify(body)}),"Supervisor override recorded.")} />}
  </>;
}

function SupervisorTable({rows,busy,onEdit,onReset,onDisable}:{rows:Supervisor[];busy:boolean;onEdit:(s:Supervisor)=>void;onReset:(s:Supervisor)=>void;onDisable:(s:Supervisor)=>void}) { if(!rows.length)return <div className="empty-state">No supervisors found.</div>; return <table className="sup-table"><thead><tr><th>Supervisor</th><th>ecNo</th><th>Organisation</th><th>Cost Center</th><th>Status</th><th style={{textAlign:"right"}}>Actions</th></tr></thead><tbody>{rows.map(s=>{const section=sectionOf(s);return <tr key={s.id}><td><strong>{s.name}</strong><div className="muted">{s.email}</div></td><td><strong>{s.employee?.ecNo??"Not linked"}</strong><div className="muted">{s.employee?.mobile??""}</div></td><td>{s.department?.name??"—"}<div className="muted">{section?`${section.code} · ${section.name}`:"No section"}</div></td><td>{section?.costCenter?`${section.costCenter.code} · ${section.costCenter.name}`:"—"}</td><td><span className={`badge badge--${s.active===false?"sync":"manual"}`}>{s.active===false?"Disabled":s.source}</span></td><td><div className="sup-table__actions"><button className="btn btn-ghost btn-sm" onClick={()=>onEdit(s)}>Edit</button><button disabled={busy||s.active===false} className="btn btn-secondary btn-sm" onClick={()=>onReset(s)}>Queue credentials</button>{s.source!=="SYNC"&&s.employee?.employmentType!=="CLMS"&&<button disabled={busy||s.active===false} className="btn btn-danger btn-sm" onClick={()=>onDisable(s)}>Disable</button>}</div></td></tr>})}</tbody></table>; }
function OverrideTable({rows,busy,onRevoke}:{rows:Override[];busy:boolean;onRevoke:(o:Override)=>void}) { if(!rows.length)return <div className="empty-state">No CLMS supervisor overrides found.</div>; return <table className="sup-table"><thead><tr><th>Employee</th><th>Department</th><th>Reason</th><th>Created</th><th>Status</th><th style={{textAlign:"right"}}>Actions</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><strong>{o.employee.name}</strong><div className="muted">ecNo {o.employee.ecNo}</div></td><td>{o.employee.department?.name??"—"}</td><td>{o.reason}</td><td>{new Date(o.createdAt).toLocaleDateString()}<div className="muted">{o.createdBy?.name}</div></td><td>{o.revokedAt?<span className="badge badge--sync">Revoked</span>:<span className="badge badge--manual">Active override</span>}</td><td><div className="sup-table__actions">{!o.revokedAt&&<button disabled={busy} className="btn btn-danger btn-sm" onClick={()=>onRevoke(o)}>Revoke</button>}</div></td></tr>)}</tbody></table>; }

function Shell({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) { return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal__header"><h2>{title}</h2><button className="modal__close" onClick={onClose}>×</button></div><div className="modal__body">{children}</div></div></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div className="sup-field"><label>{label}</label>{children}</div>; }
function SupervisorForm({supervisor,departments,sections,busy,onClose,onSave}:{supervisor?:Supervisor;departments:Department[];sections:Section[];busy:boolean;onClose:()=>void;onSave:(b:Record<string,unknown>)=>void}) {
  const currentSection=supervisor?sectionOf(supervisor):null; const syncOwned=Boolean(supervisor&&(supervisor.source==="SYNC"||supervisor.employee?.employmentType==="CLMS")); const [name,setName]=useState(supervisor?.name??""); const [ecNo,setEcNo]=useState(supervisor?.employee?.ecNo??""); const [email,setEmail]=useState(supervisor?.email??""); const [mobile,setMobile]=useState(supervisor?.employee?.mobile??""); const [departmentId,setDepartmentId]=useState(String(supervisor?.departmentId??"")); const [sectionId,setSectionId]=useState(String(currentSection?.id??"")); const [designation,setDesignation]=useState(""); const [category,setCategory]=useState("PAYROLL");
  const eligible=sections.filter(s=>String(s.departmentId)===departmentId);
  return <Shell title={supervisor?`Edit ${supervisor.name}`:"Register Supervisor"} onClose={onClose}><form className="sup-form" onSubmit={e=>{e.preventDefault();onSave(supervisor?(syncOwned?{sectionId:Number(sectionId)}:{name,email,mobile:mobile||null,sectionId:Number(sectionId)}):{ecNo:ecNo.trim(),name:name.trim(),email:email.trim(),mobile:mobile.trim()||null,departmentId:Number(departmentId),sectionId:Number(sectionId),designation,category,employmentType:"PAYROLL"});}}>
    <Field label="Canonical ecNo"><input required disabled={Boolean(supervisor)} value={ecNo} onChange={e=>setEcNo(e.target.value)} /></Field><Field label="Full name"><input required disabled={syncOwned} value={name} onChange={e=>setName(e.target.value)} /></Field><Field label="Email for credential delivery"><input required disabled={syncOwned} type="email" value={email} onChange={e=>setEmail(e.target.value)} /></Field><Field label="Mobile (optional)"><input disabled={syncOwned} value={mobile??""} onChange={e=>setMobile(e.target.value)} /></Field>
    <Field label="Department"><select required disabled={Boolean(supervisor)} value={departmentId} onChange={e=>{setDepartmentId(e.target.value);setSectionId("");}}><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Section"><select required value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">Select section</option>{eligible.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}{s.costCenter?` (${s.costCenter.code})`:""}</option>)}</select></Field>
    {!supervisor&&<><Field label="Designation"><input value={designation} onChange={e=>setDesignation(e.target.value)} /></Field><Field label="Category"><input value={category} onChange={e=>setCategory(e.target.value)} /></Field></>}
    <p className="sup-form__note">No password is entered here. A one-time credential is generated during secure delivery and the supervisor must change it after login.</p><div className="modal__footer" style={{padding:0,borderTop:"none"}}><button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?"Saving…":supervisor?"Save changes":"Save & queue credentials"}</button></div>
  </form></Shell>;
}
function OverrideForm({employees,busy,onClose,onSave}:{employees:Employee[];busy:boolean;onClose:()=>void;onSave:(b:Record<string,unknown>)=>void}) { const eligible=employees.filter(e=>e.active!==false&&e.employmentType==="CLMS"); const [employeeId,setEmployeeId]=useState("");const [reason,setReason]=useState("");return <Shell title="Add CLMS Supervisor Override" onClose={onClose}><form className="sup-form" onSubmit={e=>{e.preventDefault();onSave({employeeId:Number(employeeId),reason:reason.trim()});}}><Field label="Active CLMS employee"><select required value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Select employee</option>{eligible.map(e=><option key={e.id} value={e.id}>{e.ecNo} · {e.name}</option>)}</select></Field><Field label="Reason for manual promotion"><textarea required rows={3} value={reason} onChange={e=>setReason(e.target.value)} /></Field><p className="sup-form__note">This audited override grants supervisor capability even when CLMS Nature Of Work is not Supervisor. Revoke it when no longer needed.</p><div className="modal__footer" style={{padding:0,borderTop:"none"}}><button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?"Saving…":"Record override"}</button></div></form></Shell>; }
